// Random auto shop data that is added to Firestore
// After you've signed into the app, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  autoShopNames: [
    "Quick Fix Auto",
    "Precision Motors",
    "Budget Brake & Tire",
    "Elite Auto Service",
    "Reliable Repairs",
    "Speed Demon Garage",
    "Honest Mechanics",
    "Pro Auto Care",
    "Express Auto Works",
    "Master Tech Motors",
    "Auto Excellence",
    "Premier Auto Service",
    "Trusted Auto Repair",
    "Advanced Auto Solutions",
    "Complete Car Care",
    "Expert Auto Works",
    "Quality Auto Service",
    "Professional Motors",
    "Superior Auto Care",
    "Ace Auto Repair",
    "Top Gear Garage",
    "Prime Auto Service",
    "Elite Car Care",
    "Pro Auto Solutions",
    "Advanced Motors",
    "Expert Car Service",
    "Quality Repairs",
    "Professional Auto",
    "Superior Motors",
    "Ace Car Care",
    "Top Auto Works",
    "Prime Car Service",
    "Elite Auto Works",
    "Pro Car Care",
    "Advanced Auto Care",
    "Expert Motors",
    "Quality Auto Works",
    "Professional Car Care",
    "Superior Auto Works",
    "Ace Motors",
    "Top Car Service",
    "Prime Auto Care",
    "Elite Motors",
    "Pro Auto Works",
    "Advanced Car Service",
    "Expert Auto Care",
    "Quality Motors",
    "Professional Auto Works",
    "Superior Car Care",
    "Ace Auto Works",
  ],
  autoShopCities: [
    "New York",
    "Los Angeles",
    "London",
    "Paris",
    "Tokyo",
    "Mumbai",
    "Dubai",
    "Amsterdam",
    "Seoul",
    "Singapore",
    "Istanbul",
  ],
  autoShopCategories: [
    "General Repair",
    "Body Shop",
    "Performance Tuning",
    "Oil Change",
    "Tire Service",
    "Transmission Repair",
    "Brake Service",
    "Electrical",
    "Diagnostics",
    "Detailing",
    "Engine Repair",
    "AC Service",
    "Exhaust System",
    "Suspension",
    "Alignment",
  ],
  autoShopReviews: [
    { text: "Excellent service! Fixed my car quickly and honestly.", rating: 5 },
    { text: "Great mechanics, fair pricing, and honest work!", rating: 5 },
    { text: "Professional service and quality repairs.", rating: 5 },
    { text: "Friendly staff and reliable auto service.", rating: 5 },
    { text: "Outstanding workmanship and customer service!", rating: 5 },
    {
      text: "My car runs like new after their service. Highly recommended!",
      rating: 5,
    },
    { text: "Honest mechanics who explained everything clearly.", rating: 5 },
    { text: "Fast, reliable, and reasonably priced service.", rating: 5 },
    { text: "Good service and fair prices.", rating: 4 },
    { text: "Satisfied with the work, would return.", rating: 4 },
    { text: "Decent service and reasonable rates.", rating: 4 },
    { text: "Service was okay, but could be more thorough.", rating: 3 },
    { text: "Average experience, nothing exceptional.", rating: 3 },
    { text: "The work was adequate, but took longer than expected.", rating: 3 },
    {
      text: "Service was slow and the quality was disappointing.",
      rating: 2,
    },
    { text: "Expected better workmanship for the price.", rating: 2 },
    { text: "Poor communication and subpar repairs.", rating: 2 },
    { text: "Disappointing service overall.", rating: 2 },
    {
      text: "Terrible service, will never go back again.",
      rating: 1,
    },
    {
      text: "Worst auto shop experience I've ever had.",
      rating: 1,
    },
    { text: "Avoid this place, they damaged my car.", rating: 1 },
    { text: "Unprofessional service and poor work quality.", rating: 1 },
    { text: "Simply outstanding! Best auto service in town.", rating: 5 },
    { text: "Couldn't be happier with their work.", rating: 5 },
    { text: "Top-notch quality, worth every penny.", rating: 5 },
    { text: "Highly recommended for all auto needs.", rating: 5 },
    { text: "Expert mechanics who know their stuff.", rating: 5 },
    { text: "A gem of a shop, impeccable service.", rating: 5 },
    { text: "Excellent selection of services available.", rating: 5 },
    { text: "A fantastic auto service experience overall.", rating: 5 },
    {
      text: "The shop was clean and well-organized, professional atmosphere.",
      rating: 4,
    },
    { text: "Good work, but the service could be faster.", rating: 4 },
    {
      text: "Pleasantly surprised by the quality of work.",
      rating: 4,
    },
    { text: "Well-trained mechanics and friendly staff.", rating: 4 },
    { text: "Satisfying service, suitable for regular maintenance.", rating: 4 },
    { text: "The work was okay, nothing special.", rating: 3 },
    {
      text: "Service could be better, but the quality was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the price.", rating: 2 },
    { text: "Mediocre work and lackluster service.", rating: 2 },
    {
      text: "Regret spending money on such disappointing service.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
